# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 299ffc5479c0d50890d2573b074a87f370b7de23f43e836c7778d9d2ad24b83ca8f4d5ccab0e42251d101700085a463520c5a43003c83972176d1d35430c4488

test:
  secret_key_base: 9acae189d30d5ebc423907efa26577b83958ff5d6c56769aed55942c8fda9dead4938d26a98e3a1335210ab10e5a7715d34335718c31a0e00eb44db2fd58a3d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
